In [50]:
#importng the libraies:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report

In [51]:
#loading dataset:
movie=pd.read_csv("D:\SEM 4\Movie_classification.csv")

In [52]:
movie

Marketing expense  Production expense  Multiplex coverage     Budget  \
0              20.1264               59.62               0.462  36524.125   
1              20.5462               69.14               0.531  35668.655   
2              20.5458               69.14               0.531  39912.675   
3              20.6474               59.36               0.542  38873.890   
4              21.3810               59.36               0.542  39701.585   
..                 ...                 ...                 ...        ...   
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0           138.7               7.825                8.095            7.910   
1           152.4               7.505                7.650            7.440   
2           134.6               7.485                7.570            7.495   
3           119.3               6.895                7.035            6.920   
4           127.7               6.920                7.070            6.815   
..            ...                 ...                  ...              ...   
501         142.6               8.680                8.775            8.620   
502         150.2               8.780                8.945            8.770   
503         164.5               8.830                8.970            8.855   
504         162.8               8.730                8.845            8.800   
505         154.3               8.640                8.880            8.680   

     Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0              7.995           7.94         527367          YES      109.60   
1              7.470           7.44         494055           NO      146.64   
2              7.515           7.44         547051           NO      147.88   
3              7.020           8.26         516279          YES      185.36   
4              7.070           8.26         531448           NO      176.48   
..               ...            ...            ...          ...         ...   
501            8.970           6.80         492480           NO      186.96   
502            8.930           7.80         482875          YES      132.24   
503            9.010           7.80         532239           NO      109.56   
504            8.845           6.80         496077          YES      158.80   
505            8.790           6.80         518438          YES      205.60   

     Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0            223.840  Thriller              23            494       48000   
1            243.456     Drama              42            462       43200   
2           2022.400    Comedy              38            458       69400   
3            225.344     Drama              45            472       66800   
4            225.792     Drama              55            395       72400   
..               ...       ...             ...            ...         ...   
501          243.584    Action              27            561       44800   
502          263.296    Action              20            600       41200   
503          243.824    Comedy              31            576       47800   
504          303.520    Comedy              47            607       44000   
505          203.040    Comedy              45            604       38000   

     Start_Tech_Oscar  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
501                 0  
502                 0  
503                 0  
504              

In [53]:
#dataset information:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [54]:
print(movie['Genre'].unique())
print(movie['3D_available'].unique())

['Thriller' 'Drama' 'Comedy' 'Action']
['YES' 'NO']


In [55]:
#cathegorical to numerical:
movie['Genre']=movie['Genre'].map({'Thriller':0,'Drama':1,'Comedy':2,'Action':3})
movie['3D_available']=movie['3D_available'].map({'YES':1,'NO':0})

In [56]:
movie.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  3D_available  Time_taken  \
0            7.995           7.94         527367             1      109.60   
1            7.470           7.44         494055             0      146.64   
2            7.515           7.44         547051             0      147.88   
3            7.020           8.26         516279             1      185.36   
4            7.070           8.26         531448             0      176.48   

   Twitter_hastags  Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840      0              23            494       48000   
1          243.456      1              42            462       43200   
2         2022.400      2              38            458       69400   
3          225.344      1              45            472       66800   
4          225.792      1              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [57]:
#checkig the null values:
movie.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [58]:
#changing the null values with mean:
movie['Time_taken'].fillna(movie['Time_taken'].mean(),inplace=True)

In [59]:
movie.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [60]:
# Feature Scaling:
n=movie.iloc[:,:-1]
movie.iloc[:,:-1]=(n-n.min())/(n.max()-n.min())

In [61]:
movie

Marketing expense  Production expense  Multiplex coverage    Budget  \
0             0.000000            0.067815            0.685185  0.577505   
1             0.000236            0.242302            0.827160  0.547998   
2             0.000236            0.242302            0.827160  0.694386   
3             0.000293            0.063050            0.849794  0.658555   
4             0.000705            0.063050            0.849794  0.687105   
..                 ...                 ...                 ...       ...   
501           0.000633            0.420455            0.613169  0.580954   
502           0.000438            0.420455            0.613169  0.490324   
503           0.000612            0.420455            0.613169  0.654340   
504           0.001161            0.420455            0.613169  0.619467   
505           0.000462            0.420455            0.613169  0.473079   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0        0.641607            0.712243             0.737511         0.728738   
1        0.782698            0.655049             0.656676         0.644584   
2        0.599382            0.651475             0.642144         0.654432   
3        0.441813            0.546023             0.544959         0.551477   
4        0.528321            0.550492             0.551317         0.532677   
..            ...                 ...                  ...              ...   
501      0.681771            0.865058             0.861035         0.855864   
502      0.760041            0.882931             0.891916         0.882722   
503      0.907312            0.891868             0.896458         0.897941   
504      0.889804            0.873995             0.873751         0.888093   
505      0.802266            0.857909             0.880109         0.866607   

     Producer_rating  Critic_rating  Trailer_views  3D_available  Time_taken  \
0           0.707404       0.478571       0.886108           1.0    0.503862   
1           0.613738       0.300000       0.792238           0.0    0.674145   
2           0.621766       0.300000       0.941576           0.0    0.679846   
3           0.533452       0.592857       0.854863           1.0    0.852152   
4           0.542373       0.592857       0.897608           0.0    0.811328   
..               ...            ...            ...           ...         ...   
501         0.881356       0.071429       0.787800           0.0    0.859507   
502         0.874219       0.428571       0.760733           1.0    0.607944   
503         0.888492       0.428571       0.899837           0.0    0.503678   
504         0.859054       0.071429       0.797936           1.0    0.730048   
505         0.849242       0.071429       0.860947           1.0    0.945200   

     Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0           0.012457  0.000000        0.350877       0.300935    0.422222   
1           0.023228  0.333333        0.684211       0.241121    0.368889   
2           1.000000  0.666667        0.614035       0.233645    0.660000   
3           0.013283  0.333333        0.736842       0.259813    0.631111   
4           0.013529  0.333333        0.912281       0.115888    0.693333   
..               ...       ...             ...            ...         ...   
501         0.023298  1.000000        0.421053       0.426168    0.386667   
502         0.034122  1.000000        0.298246       0.499065    0.346667   
503         0.023430  0.666667        0.491228       0.454206    0.420000   
504         0.056208  0.666667        0.771930       0.512150    0.377778   
505         0.001037  0.666667        0.736842       0.506542    0.311111   

     Start_Tech_Oscar  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
501                 0  
502                 0  
503                 0  
504              

In [62]:
#spliting dataset into feature and traget values:
x=movie.iloc[:,:-1].values
y=movie.iloc[:,-1].values

In [63]:
x

array([[0.00000000e+00, 6.78152493e-02, 6.85185185e-01, ...,
        3.50877193e-01, 3.00934579e-01, 4.22222222e-01],
       [2.35922539e-04, 2.42302053e-01, 8.27160494e-01, ...,
        6.84210526e-01, 2.41121495e-01, 3.68888889e-01],
       [2.35697744e-04, 2.42302053e-01, 8.27160494e-01, ...,
        6.14035088e-01, 2.33644860e-01, 6.60000000e-01],
       ...,
       [6.11892474e-04, 4.20454545e-01, 6.13168724e-01, ...,
        4.91228070e-01, 4.54205607e-01, 4.20000000e-01],
       [1.16072990e-03, 4.20454545e-01, 6.13168724e-01, ...,
        7.71929825e-01, 5.12149533e-01, 3.77777778e-01],
       [4.61841693e-04, 4.20454545e-01, 6.13168724e-01, ...,
        7.36842105e-01, 5.06542056e-01, 3.11111111e-01]])

In [64]:
y

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,

In [65]:
#reducing the dataset 3 components:
pca=PCA()
pca=PCA(n_components=3)

In [66]:
x=pca.fit_transform(x)

In [67]:
x

array([[ 0.40742044, -0.42044449, -0.39122249],
       [ 0.14497383,  0.58137599, -0.09533055],
       [ 0.29689664,  0.61712302,  0.23178793],
       ...,
       [-0.35767705,  0.45923249,  0.16198093],
       [-0.22348541, -0.50350684,  0.25296987],
       [-0.18424372, -0.47879824,  0.26279496]])

In [68]:
#Splitting the dataset into the Training set and Test set:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [69]:
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(x_test))

354
354
152
152


In [70]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,

In [71]:
# Training the Logistic Regression model:
lg=LogisticRegression()
lg.fit(x_train,y_train)

LogisticRegression()

In [72]:
# Predicting the Test set results:
predict=lg.predict(x_test)

In [73]:
predict

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [74]:
#prtinting the accuracy score:
print('accuracy score:',metrics.accuracy_score(y_test,predict))

accuracy score: 0.5394736842105263


In [75]:
#priting the classification report:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.41      0.24      0.30        63
           1       0.58      0.75      0.66        89

    accuracy                           0.54       152
   macro avg       0.49      0.50      0.48       152
weighted avg       0.51      0.54      0.51       152

