In [54]:
import pandas as pd
import numpy as np
import math


In [3]:
data=pd.read_csv("D:\sem 3\iris.csv")

In [4]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
#checking null values
data.isnull().sum()


sepal_length    0
sepal_width     2
petal_length    3
petal_width     2
species         0
dtype: int64

In [11]:
#replaceing null values
data['sepal_width'].fillna(data['sepal_width'].mean(),inplace=True)
data['petal_length'].fillna(data['petal_length'].mean(),inplace=True)
data['petal_width'].fillna(data['petal_width'].mean(),inplace=True)

In [12]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [14]:
#checking info of data
data.info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [17]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
data.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [16]:
#spliting coloumn 
data.iloc[:5]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
#taking indituval coloumn
data['species']


0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [40]:
#spliting coloumns only
x=data.iloc[:,0:4].values
x1=data.iloc[:,[0,1,2,3]].values

In [27]:
x

array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.1       , 1.5       , 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ],
       [5.4       , 3.9       , 1.7       , 0.4       ],
       [4.6       , 3.4       , 1.4       , 1.21216216],
       [5.        , 3.4       , 1.5       , 0.2       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       , 1.3       , 0.4       ],
       [5.1       , 3.5       ,

In [43]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [41]:
#taking only traget value
y=data.iloc[:,4].values
y1=data.iloc[:,-1].values

In [42]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [39]:
#importing from sklearn for training,test, and spliting
from sklearn.model_selection import train_test_split

In [46]:
#storing training input and outputs values,storing input and outputs of testing
#spliting for training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [47]:
x_train

array([[5.9       , 3.        , 4.2       , 1.5       ],
       [5.8       , 2.6       , 4.        , 1.2       ],
       [6.8       , 3.        , 5.5       , 2.1       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [6.9       , 3.1       , 5.1       , 2.3       ],
       [5.        , 3.5       , 1.6       , 0.6       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [5.        , 2.        , 3.5       , 1.        ],
       [6.5       , 3.        , 5.5       , 1.8       ],
       [6.7       , 3.3       , 5.7       , 2.5       ],
       [6.        , 2.2       , 5.        , 1.5       ],
       [6.7       , 2.5       , 5.8       , 1.8       ],
       [5.6       , 2.5       , 3.9       , 1.1       ],
       [7.7       , 3.        , 6.1       , 2.3       ],
       [6.3       , 3.3       , 3.78163265, 1.6       ],
       [5.5       , 2.4       , 3.8       , 1.1       ],
       [6.3       , 2.7       , 4.9       , 1.8       ],
       [6.3       , 2.8       ,

In [48]:
x_test

array([[5.8       , 2.8       , 5.1       , 2.4       ],
       [6.        , 2.2       , 4.        , 1.        ],
       [5.5       , 4.2       , 1.4       , 0.2       ],
       [7.3       , 2.9       , 6.3       , 1.8       ],
       [5.        , 3.4       , 1.5       , 0.2       ],
       [6.3       , 3.3       , 6.        , 2.5       ],
       [5.        , 3.5       , 1.3       , 0.3       ],
       [6.7       , 3.1       , 4.7       , 1.5       ],
       [6.8       , 2.8       , 4.8       , 1.4       ],
       [6.1       , 2.8       , 4.        , 1.3       ],
       [6.1       , 2.6       , 5.6       , 1.4       ],
       [6.4       , 3.2       , 4.5       , 1.5       ],
       [6.1       , 2.8       , 4.7       , 1.2       ],
       [6.5       , 2.8       , 4.6       , 1.5       ],
       [6.1       , 2.9       , 4.7       , 1.4       ],
       [4.9       , 3.6       , 1.4       , 0.1       ],
       [6.        , 2.9       , 4.5       , 1.5       ],
       [5.5       , 2.6       ,

In [49]:
y_train

array(['versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'setosa', 'setosa', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'setosa'

In [50]:
y_test

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'versicolor'], dtype=object)

In [58]:
#cehcking the no of iteams in a array
len(x_train)

112

In [59]:
len(y_train)

112

In [61]:
len(x_test)


38

In [62]:
len(y_test)

38

In [69]:
#importing knn algoritham
from sklearn.neighbors import KNeighborsClassifier

In [71]:
#creating knn model
classifier=KNeighborsClassifier(n_neighbors=13,metric='minkowski',p=2)

In [72]:
#fiting the feature vale and traget value
classifier.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=13)

In [73]:
#Here predicting with the feature test value
y_predict=classifier.predict(x_test)

In [76]:
#checking accuracy of the model
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_predict))

0.9736842105263158


In [82]:
#checking accuracy of the model using cm
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)

In [83]:
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [85]:
#creating new data using numpy
x_new=np.array([[5,2.8,1,0.2],[3,1.9,.9,7.2],[6,8.9,2.1,3.8]])

In [86]:
prediction=classifier.predict(x_new)

In [87]:
prediction

array(['setosa', 'versicolor', 'setosa'], dtype=object)